<?php /*?><script src="<?php echo $this->getskinUrl('slider/jquery.bxslider.min.js')?>" type="text/javascript"></script>
<link href="<?php echo $this->getskinUrl('slider/jquery.bxslider.css')?>" rel="stylesheet" type="text/css" /><?php */?>
<?php $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode(); ?>
<div class="slider">
<?php if($currency_code == 'USD'){?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_page_banner_usd')->toHtml() ?>
<?php }else{?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_page_banner')->toHtml() ?>
<?php }?>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.bxslider').bxSlider({auto: true});	
});
</script>
<div class="left_banner">
<?php if($currency_code == 'USD'){?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_right_banner_usd')->toHtml() ?>
<?php }else{?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_right_banner')->toHtml() ?>
<?php }?>
</div>
<?php if($currency_code == 'USD'){?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_promo_block_usd')->toHtml() ?>
<?php }else{?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_promo_block')->toHtml() ?>
<?php }?>
<?php 
$categoryId = 7;
$products = Mage::getSingleton('catalog/category')->load($categoryId)
->getProductCollection()
->addAttributeToSelect('*');
if($products){
?>
<div class="home-category-products">
	    <ul class="home-products-grid">
	    	<?php foreach ($products as $_product): ?>
	    		<li class="product_item">
	    		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(204,192); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>                
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title=""><?php echo $_product->getName(); ?></a></h2>
                
               <?php 
                $fprice = $_product->getFinalPrice();
                $rprice = $_product->getPrice();
                if($fprice == $rprice){
                ?>
                <div class="price">
                	<div class="rprice"><?php echo number_format($rprice,0); ?><sup><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?></sup></div>
                </div>                
                <?php } else {?>
                 <div class="price special">
                	<div class="rprice"><?php echo number_format($rprice,0); ?><sup><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?></sup></div>
                	<div class="spprice"><?php echo number_format($fprice,2, ',', ' '); ?><sup><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?></sup></div>
                </div>    
                <?php } ?>
                </li>
	    	 <?php endforeach ?>
		</ul>
</div>
<?php } ?>


<?php 
$categoryId = 8;
$products = Mage::getSingleton('catalog/category')->load($categoryId)
->getProductCollection()
->addAttributeToSelect('*');
$i=0;
if($products){
?>
<div class="home-category-products home-promo">
	    <ul class="home-products-grid">
	    	<?php foreach ($products as $_product): ?>
	    		<?php $i++; ?>
	    		<li class="product_item <?php if($i == 3){ echo "last"; }?>">
	    		<img src="<?php echo $this->getskinUrl('images/sticker_promo.png')?>" class="promo_sticker" />
	    		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(204,192); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>                
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title=""><?php echo $_product->getName(); ?></a></h2>
                
                <?php 
                $fprice = $_product->getFinalPrice();
                $rprice = $_product->getPrice();
                if($fprice == $rprice){
                ?>
                <div class="price">
                	<div class="rprice"><?php echo number_format($rprice,0); ?><sup><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?></sup></div>
                </div>                
                <?php } else {?>
                 <div class="price special">
                	<div class="rprice"><?php echo number_format($rprice,0); ?><sup><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?></sup></div>
                	<div class="spprice"><?php echo number_format($fprice,2, ',', ' '); ?><sup><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();?></sup></div>
                </div>    
                <?php } ?>
                </li>
	    	 <?php endforeach ?>
	    	 <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_product_promo')->toHtml() ?>
		</ul>
</div>
<?php } ?>